name: Deploy Spring Boot Application to AWS Elastic Beanstalk
on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Build and Test Spring Boot Application"]
  #   types:
  #     - completed

jobs:
  deploy:
    name: Deploy Spring Boot Application to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: target/

      - name: Deploy to AWS ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          region: us-east-1  # Replace with your AWS region
          aws_access_key: ${{ secrets.YOUR_AWS_ACCESS_KEY_ID }}  # Replace with your AWS access key ID stored in GitHub secrets
          aws_secret_key: ${{ secrets.YOUR_AWS_SECRET_ACCESS_KEY }}  # Replace with your AWS secret access key stored in GitHub secrets
          application_name: your-application-name  # Replace with your Elastic Beanstalk application name
          environment_name: your-environment-name  # Replace with your Elastic Beanstalk environment name
          version_label: ${{ github.run_number }}  # Optional: you can customize the version label
          use_existing_version_if_available: true
          deployment_package: target/*.jar
      
      - run: echo "Deployment completed successfully!"
